checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ["pyof/*", "test/*"]
build:
    environment:
        python: 3.12
        postgresql: True
        redis: false
    dependencies:
        override:
            - true
    tests:
        before:
            - pip install coverage
        override:
            - py-scrutinizer-run