services:
  server:
    env_file:
      - .env
    image: python:3.12.4
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
    command: python -m flask run -p 3000 --host=0.0.0.0 --reload --debug

  redis:
    image: redis:latest
    environment:
      FLASK_APP: src/server
    volumes:
      - .:/src
    ports:
      - 6379:6379

  celery:
    build:
        context: .
    environment:
      FLASK_APP: src/server
    volumes:
      - .:/src
    command: celery -A run.celery worker --loglevel=info
    depends_on:
      - redis

  dbdata:
    image: busybox
    volumes:
      - /var/lib/postgresql/data
  db:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes_from:
      - dbdata

  testserver:
    env_file: .env
    image: python:3.12.4
    working_dir: /mnt
    volumes:
      - .:/mnt
    depends_on:
      - testdb
    ports:
      - 5053:5053
    environment:
      APPLICATION_PORT: 5053
      APPLICATION_DB_CONTAINER: testdb
    command: python -m pytest test/

  testdb:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGPORT: 5433
    ports:
      - "5433:5433"
