"""empty message

Revision ID: 27fd31c60925
Revises: None
Create Date: 2024-06-26 07:48:11.606951

"""

# revision identifiers, used by Alembic.
revision = '27fd31c60925'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debit',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('governmentId', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=300), nullable=False),
    sa.Column('debtAmount', sa.Float(), nullable=False),
    sa.Column('debtDueDate', sa.Date(), nullable=False),
    sa.Column('debtID', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('debtID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debit')
    # ### end Alembic commands ###